### ISSUE TITLE
请问下视频制作工具和ios端、web端会开源吗？

### ISSUE THREAD

**Issue by jtyang** [bytedance/AlphaPlayer#1]
RT

**Comment by crazy1235** [comment]
通过AE可导出标注rgb的mp4和 灰度图像的mp4。然后通过ffmpeg 合成一个视频即可

**Comment by DymanZy** [comment]
@jtyang 视频制作工具方面的问题 @crazy1235 已经帮忙回答了，实际上AE还支持直接将标注rgb的mp4和灰度图的mp4合成一个视频输出。目前iOS端的开源还在准备中，web端暂时不支持

**Comment by qq326646683** [comment]
期待ios端的开源
