### ISSUE TITLE
播放器用了exoplayer，用于直播的场景没有软硬解码切换

### ISSUE THREAD

**Issue by JeffMony** [bytedance/AlphaPlayer#10]
应该还有native的ttplay

**Comment by DymanZy** [comment]
直播场景是分拉流播放器和礼物特效播放器的，其中拉流是基于自研播放器的，与特效使用的播放器是否开启软硬解互不影响，需要的话你可以关注一下这个回答 -> https://github.com/bytedance/AlphaPlayer/issues/8
