### ISSUE TITLE
请问是否可以设置循环播放

### ISSUE THREAD

**Issue by chinkeikin** [bytedance/AlphaPlayer#11]

**Comment by DymanZy** [comment]
@sinkkin 在1.0.5版本支持了，可以通过 `DataSource#setLooping(isLooping: Boolean)` 设置

**Comment by ke112** [comment]
急急急!!!!   楼主,我想自动播放视频的操作,没有找到你说的这个 DataSource#setLooping(isLooping: Boolean),,最新版本  iOS  1.2.2
