### ISSUE TITLE
Demo获取路径有问题，建议改一下

### ISSUE THREAD

**Issue by aJanefish** [bytedance/AlphaPlayer#15]
private fun getResourcePath(): String {
        val dirPath = basePath + File.separator + "alphaVideoGift" + File.separator
        val dirFile = File(dirPath)
        if (dirFile.exists() && dirFile.listFiles() != null && dirFile.listFiles().isNotEmpty()) {
            return dirFile.listFiles()[0].absolutePath
        }
        return ""
    }

    //dirFile.listFiles()[0].absolutePath  /storage/emulated/0/alphaVideoGift/config.json
    //dirFile.listFiles()[0].parent /storage/emulated/0/alphaVideoGift

你们期望的应该是parent的路径，建议修改一下

**Comment by DymanZy** [comment]
路径是没有错的，可以检查一下你执行资源导入指令是：gift_install.sh gift/demoRes  还是 gift_install.sh gift/demoRes/

**Comment by DymanZy** [comment]
@aJanefish 路径是没有错的，可以检查一下你执行资源导入指令是：gift_install.sh gift/demoRes  还是 gift_install.sh gift/demoRes/
使用前者导入时 getResourcePath() 获取到的路径是 /storage/emulated/0/alphaVideoGift/demoRes
使用后者导入时 getResourcePath() 获取到的路径是 /storage/emulated/0/alphaVideoGift/config.json
