### ISSUE TITLE
请问一下我用convertAlphaVideo.py脚本为什么会转换失败

### ISSUE THREAD

**Issue by hehuiran** [bytedance/AlphaPlayer#16]
![16046399178073](https://user-images.githubusercontent.com/23009126/98329244-bc079800-2032-11eb-9feb-5b544d993b8d.png)
这是脚本执行信息

**Comment by hehuiran** [comment]
无效参数 - /爱心雨_00116.png
无效参数 - C:\Users\Administrator\Desktop\b
progress : 95.9% [117/122]无效参数 - /爱心雨_00117.png
无效参数 - /爱心雨_00117.png
无效参数 - C:\Users\Administrator\Desktop\b
progress : 96.72% [118/122]无效参数 - /爱心雨_00118.png
无效参数 - /爱心雨_00118.png
无效参数 - C:\Users\Administrator\Desktop\b
progress : 97.54% [119/122]无效参数 - /爱心雨_00119.png
无效参数 - /爱心雨_00119.png
无效参数 - C:\Users\Administrator\Desktop\b
progress : 98.36% [120/122]ffmpeg version 4.2.3 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9.3.1 (GCC) 20200523
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
[image2 @ 000002a79f639cc0] Could find no file with path 'C:\Users\Administrator\Desktop\b/temp/output/%05d.jpg' and index in the range 0-4
C:\Users\Administrator\Desktop\b/temp/output/%05d.jpg: No such file or directory
>>>>>> convert alpha video finish, video file path is : C:\Users\Administrator\Desktop\b/output/video.mp4
finish

**Comment by DymanZy** [comment]
可以提供一下你的素材？

**Comment by DymanZy** [comment]
@hehuiran  看你的运行日志，应该将"爱心雨_00xxx.png"统一改为"00xxx.png"再运行就可以了

**Comment by hehuiran** [comment]
无效参数 - C:\Users\Administrator\Desktop\dsv
progress : 86.89% [106/122]无效参数 - /00106.png
无效参数 - /00106.png
无效参数 - C:\Users\Administrator\Desktop\dsv
progress : 87.7% [107/122]无效参数 - /00107.png
无效参数 - /00107.png
无效参数 - C:\Users\Administrator\Desktop\dsv
progress : 88.52% [108/122]无效参数 - /00108.png
无效参数 - /00108.png
无效参数 - C:\Users\Administrator\Desktop\dsv
progress : 89.34% [109/122]无效参数 - /00109.png
无效参数 - /00109.png
无效参数 - C:\Users\Administrator\Desktop\dsv
progress : 90.16% [110/122]无效参数 - /00110.png
无效参数 - /00110.png
无效参数 - C:\Users\Administrator\Desktop\dsv
progress : 90.98% [111/122]无效参数 - /00111.png
无效参数 - /00111.png
无效参数 - C:\Users\Administrator\Desktop\dsv
progress : 91.8% [112/122]无效参数 - /00112.png
无效参数 - /00112.png
无效参数 - C:\Users\Administrator\Desktop\dsv
progress : 92.62% [113/122]无效参数 - /00113.png
无效参数 - /00113.png
无效参数 - C:\Users\Administrator\Desktop\dsv
progress : 93.44% [114/122]无效参数 - /00114.png
无效参数 - /00114.png
无效参数 - C:\Users\Administrator\Desktop\dsv
progress : 94.26% [115/122]无效参数 - /00115.png
无效参数 - /00115.png
无效参数 - C:\Users\Administrator\Desktop\dsv
progress : 95.08% [116/122]无效参数 - /00116.png
无效参数 - /00116.png
无效参数 - C:\Users\Administrator\Desktop\dsv
progress : 95.9% [117/122]无效参数 - /00117.png
无效参数 - /00117.png
无效参数 - C:\Users\Administrator\Desktop\dsv
progress : 96.72% [118/122]无效参数 - /00118.png
无效参数 - /00118.png
无效参数 - C:\Users\Administrator\Desktop\dsv
progress : 97.54% [119/122]无效参数 - /00119.png
无效参数 - /00119.png
无效参数 - C:\Users\Administrator\Desktop\dsv
progress : 98.36% [120/122]ffmpeg version 4.2.3 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9.3.1 (GCC) 20200523
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
[image2 @ 0000017c95fb9cc0] Could find no file with path 'C:\Users\Administrator\Desktop\dsv/temp/output/%05d.jpg' and index in the range 0-4
C:\Users\Administrator\Desktop\dsv/temp/output/%05d.jpg: No such file or directory
>>>>>> convert alpha video finish, video file path is : C:\Users\Administrator\Desktop\dsv/output/video.mp4
finish
![16050778144716](https://user-images.githubusercontent.com/23009126/98779064-3ae34300-242e-11eb-9424-b4c7ac067a4e.png)

**Comment by hehuiran** [comment]
图片改名之后还是一样的，我把文件发到你邮箱了，麻烦大佬帮忙看下是什么问题

**Comment by solomon2** [comment]
@hehuiran 老哥这个问题你解决了吗   我也遇到同样的问题

@DymanZy 大佬
![1](https://user-images.githubusercontent.com/1875409/117392995-bcbbb100-af25-11eb-95c5-de62d79b1d5a.png)
![2](https://user-images.githubusercontent.com/1875409/117393005-c3e2bf00-af25-11eb-923b-3eb2dfcefc6b.png)
如果我手动把png图片转为jpg然后运行convertAlphaVideo就可以生成视频文件， 不过只有一半 ，没有demo 里面的左右视频带透明通道的

**Comment by igo9go** [comment]
一样报错

**Comment by Androidkobe** [comment]
一样报错

**Comment by TeeMoYan** [comment]
> 图片改名之后还是一样的，我把文件发到你邮箱了，麻烦大佬帮忙看下是什么问题

请问解决了吗？

**Comment by lybill** [comment]
一样报错，有知道的大佬吗？

**Comment by ke112** [comment]
一样报错，有知道的大佬吗？

**Comment by Yuxiang-Tsai** [comment]
一样报错，有知道的大佬吗？

**Comment by Yuxiang-Tsai** [comment]
https://github.com/bytedance/AlphaPlayer/issues/105
我之前也报错，这是我的解决方法 @hehuiran @igo9go @lybill
