### ISSUE TITLE
播放的视频太过透明

### ISSUE THREAD

**Issue by gnmmdk** [bytedance/AlphaPlayer#18]
你好，我用 ffmpeg -i right.mp4 -vf lutyuv="u=128:v=128" left.mp4 和 ffmpeg -re -i left.mp4 -re -i right.mp4 -filter_complex "nullsrc=size=2160x1920 [base]; [0:v] scale=1080x1920 [left]; [1:v] scale=1080x1920 [right]; [base][left] overlay=shortest=1 [tmp1]; [tmp1][right] overlay=shortest=1:x=1080" -c:v libx264 -pix_fmt yuv420p -movflags faststart -f mp4 left_right.mp4
这两个指令生成了视频，
![image](https://user-images.githubusercontent.com/18391426/98517116-64726200-22a8-11eb-9946-23a9a1a78712.png)
但是播放出来的颜色太浅了，
![image](https://user-images.githubusercontent.com/18391426/98516975-37be4a80-22a8-11eb-9734-c6196ee4af6a.png)

是视频的问题吗？还是什么？请问如何解决？

**Comment by gnmmdk** [comment]
![image](https://user-images.githubusercontent.com/18391426/98517231-89ff6b80-22a8-11eb-8c66-d5418bf422ca.png)

**Comment by DymanZy** [comment]
左边的透明通道生成不对，左边主体的RGB值是（198, 198, 198），就意味着你混合后的动画是透明度是0.77的

**Comment by gnmmdk** [comment]
> 左边的透明通道生成不对，左边主体的RGB值是（198, 198, 198），就意味着你混合后的动画是透明度是0.77的
你好，左边主体的RGB值是（198, 198, 198）这个是怎么看出来的呢？我上方的指令需要做什么修改？

**Comment by gnmmdk** [comment]
> 左边的透明通道生成不对，左边主体的RGB值是（198, 198, 198），就意味着你混合后的动画是透明度是0.77的

你好，左边主体的RGB值是（198, 198, 198）这个是怎么看出来的呢？我上方的指令需要做什么修改？

**Comment by aceprcet** [comment]
> > 左边的透明通道生成不对，左边主体的RGB值是（198, 198, 198），就意味着你混合后的动画是透明度是0.77的
> 
> 你好，左边主体的RGB值是（198, 198, 198）这个是怎么看出来的呢？我上方的指令需要做什么修改？

左侧的黑白遮罩并不是灰度信息，而是透明度信息。你的第一个指令是分离出灰度信息放在左侧，因此最终混合的效果不太对。
另外，mp4文件是不带有透明度信息，如果想制作视频，你需要png序列帧或者带有透明度信息的源文件(eg.mov)进行制作，推荐使用项目里的convertAlphaVideo.py进行制作哈～

**Comment by DymanZy** [comment]
> > 左边的透明通道生成不对，左边主体的RGB值是（198, 198, 198），就意味着你混合后的动画是透明度是0.77的
> 
> 你好，左边主体的RGB值是（198, 198, 198）这个是怎么看出来的呢？我上方的指令需要做什么修改？

用拾色器对比看出来的，可以参考 @aceprcet 的意见呢，导出带透明度的png序列帧再使用 convertAlphaVideo.py 可以直接导出成品素材 :)

**Comment by gnmmdk** [comment]
> > > 左边的透明通道生成不对，左边主体的RGB值是（198, 198, 198），就意味着你混合后的动画是透明度是0.77的
> > 
> > 
> > 你好，左边主体的RGB值是（198, 198, 198）这个是怎么看出来的呢？我上方的指令需要做什么修改？
> 
> 左侧的黑白遮罩并不是灰度信息，而是透明度信息。你的第一个指令是分离出灰度信息放在左侧，因此最终混合的效果不太对。
> 另外，mp4文件是不带有透明度信息，如果想制作视频，你需要png序列帧或者带有透明度信息的源文件(eg.mov)进行制作，推荐使用项目里的convertAlphaVideo.py进行制作哈～
好的，谢谢解答~
我用converAlphaVideo指令时遇到了下方的错误，可以再帮忙看下吗？
![image](https://user-images.githubusercontent.com/18391426/98762150-fb0e6280-2411-11eb-862d-9c646463b7de.png)

**Comment by gnmmdk** [comment]
> > > 左边的透明通道生成不对，左边主体的RGB值是（198, 198, 198），就意味着你混合后的动画是透明度是0.77的
> > 
> > 
> > 你好，左边主体的RGB值是（198, 198, 198）这个是怎么看出来的呢？我上方的指令需要做什么修改？
> 
> 用拾色器对比看出来的，可以参考 @aceprcet 的意见呢，导出带透明度的png序列帧再使用 convertAlphaVideo.py 可以直接导出成品素材 :)

好的，感谢解答~另外我使用converAlphaVideo.py的时候遇到了SyntaxError: Missing parentheses in call to 'print'. Did you mean print("args.zip: ", args.zip)?  
请问如何解决？

**Comment by gnmmdk** [comment]
为了解决SyntaxError: Missing parentheses in call to 'print'. Did you mean print("args.zip: ", args.zip)? 这个问题 ，我把跟args.zip相关的注释掉了，如下图
![image](https://user-images.githubusercontent.com/18391426/98781590-8ea35b80-2431-11eb-9cb8-32d8e35aa59d.png)
然后运行指令的时候遇到如下的错误
![image](https://user-images.githubusercontent.com/18391426/98781707-c27e8100-2431-11eb-88b7-55eb106eadcb.png)
部分图片如下：
![image](https://user-images.githubusercontent.com/18391426/98781855-ffe30e80-2431-11eb-9437-159b07f2985f.png)

**Comment by aceprcet** [comment]
> > > > 左边的透明通道生成不对，左边主体的RGB值是（198, 198, 198），就意味着你混合后的动画是透明度是0.77的
> > > 
> > > 
> > > 你好，左边主体的RGB值是（198, 198, 198）这个是怎么看出来的呢？我上方的指令需要做什么修改？
> > 
> > 
> > 用拾色器对比看出来的，可以参考 @aceprcet 的意见呢，导出带透明度的png序列帧再使用 convertAlphaVideo.py 可以直接导出成品素材 :)
> 
> 好的，感谢解答~另外我使用converAlphaVideo.py的时候遇到了SyntaxError: Missing parentheses in call to 'print'. Did you mean print("args.zip: ", args.zip)?
> 请问如何解决？

这个问题的原因是你安装的是python3版本，print函数需要加上小括号

**Comment by aceprcet** [comment]
> 为了解决SyntaxError: Missing parentheses in call to 'print'. Did you mean print("args.zip: ", args.zip)? 这个问题 ，我把跟args.zip相关的注释掉了，如下图
> ![image](https://user-images.githubusercontent.com/18391426/98781590-8ea35b80-2431-11eb-9cb8-32d8e35aa59d.png)
> 然后运行指令的时候遇到如下的错误
> ![image](https://user-images.githubusercontent.com/18391426/98781707-c27e8100-2431-11eb-88b7-55eb106eadcb.png)
> 部分图片如下：
> ![image](https://user-images.githubusercontent.com/18391426/98781855-ffe30e80-2431-11eb-9437-159b07f2985f.png)

这个问题是png序列帧命名的问题，你需要批量把序列帧命名改为5位数字，eg：00000.png、00001.png、00002.png....后续会优化（另外，现在使用请保证needZip是false）

**Comment by gnmmdk** [comment]
> > 为了解决SyntaxError: Missing parentheses in call to 'print'. Did you mean print("args.zip: ", args.zip)? 这个问题 ，我把跟args.zip相关的注释掉了，如下图
> > ![image](https://user-images.githubusercontent.com/18391426/98781590-8ea35b80-2431-11eb-9cb8-32d8e35aa59d.png)
> > 然后运行指令的时候遇到如下的错误
> > ![image](https://user-images.githubusercontent.com/18391426/98781707-c27e8100-2431-11eb-88b7-55eb106eadcb.png)
> > 部分图片如下：
> > ![image](https://user-images.githubusercontent.com/18391426/98781855-ffe30e80-2431-11eb-9437-159b07f2985f.png)
> 
> 这个问题是png序列帧命名的问题，你需要批量把序列帧命名改为5位数字，eg：00000.png、00001.png、00002.png....后续会优化（另外，现在使用请保证needZip是false）

上方的内容已修改如下：
![image](https://user-images.githubusercontent.com/18391426/98796463-5ce8bf80-2446-11eb-9365-6476b83e1af2.png)
![image](https://user-images.githubusercontent.com/18391426/98796528-712cbc80-2446-11eb-8562-a47ba4511cd0.png)
但是还是报错了：
![image](https://user-images.githubusercontent.com/18391426/98796643-93263f00-2446-11eb-9df0-4f680da1d279.png)

**Comment by aceprcet** [comment]
@gnmmdk 抱歉，这个是路径分隔符的问题，脚本里的是mac系统下的路径分隔符"/"，如果你是windows系统的话需要把里面的路径“/”全转换为“\\”（这个后续会优化尽量避免这个问题）。另外你的输入路径不需要加引号，直接用--dir PNG_Sequence

**Comment by gnmmdk** [comment]
> @gnmmdk 抱歉，这个是路径分隔符的问题，脚本里的是mac系统下的路径分隔符"/"，如果你是windows系统的话需要把里面的路径“/”全转换为“\”（这个后续会优化尽量避免这个问题）。另外你的输入路径不需要加引号，直接用--dir PNG_Sequence

还是不行啊，大兄弟，我改了后报分隔符错误的问题
![image](https://user-images.githubusercontent.com/18391426/98885041-49803780-24cc-11eb-8ec9-58ecc5054543.png)
你那边方便提供下window版的 convertAlphaVideo.py脚本吗？

**Comment by gnmmdk** [comment]
> @gnmmdk 抱歉，这个是路径分隔符的问题，脚本里的是mac系统下的路径分隔符"/"，如果你是windows系统的话需要把里面的路径“/”全转换为“\”（这个后续会优化尽量避免这个问题）。另外你的输入路径不需要加引号，直接用--dir PNG_Sequence

我将路径“/”改为“\\”后没有语法错误了，不过还是有问题
![image](https://user-images.githubusercontent.com/18391426/98886415-fe1b5880-24ce-11eb-8115-d81cf655c854.png)
![image](https://user-images.githubusercontent.com/18391426/98886427-06739380-24cf-11eb-8399-950863fff88b.png)
![image](https://user-images.githubusercontent.com/18391426/98886470-1db28100-24cf-11eb-9061-4166e399d744.png)

**Comment by aceprcet** [comment]
> > @gnmmdk 抱歉，这个是路径分隔符的问题，脚本里的是mac系统下的路径分隔符"/"，如果你是windows系统的话需要把里面的路径“/”全转换为“\”（这个后续会优化尽量避免这个问题）。另外你的输入路径不需要加引号，直接用--dir PNG_Sequence
> 
> 我将路径“/”改为“\”后没有语法错误了，不过还是有问题
> ![image](https://user-images.githubusercontent.com/18391426/98886415-fe1b5880-24ce-11eb-8115-d81cf655c854.png)
> ![image](https://user-images.githubusercontent.com/18391426/98886427-06739380-24cf-11eb-8399-950863fff88b.png)
> ![image](https://user-images.githubusercontent.com/18391426/98886470-1db28100-24cf-11eb-9061-4166e399d744.png)

你需要提前安装imagemagick，参考这里https://imagemagick.org/script/download.php

**Comment by gnmmdk** [comment]
> > > @gnmmdk 抱歉，这个是路径分隔符的问题，脚本里的是mac系统下的路径分隔符"/"，如果你是windows系统的话需要把里面的路径“/”全转换为“\”（这个后续会优化尽量避免这个问题）。另外你的输入路径不需要加引号，直接用--dir PNG_Sequence
> > 
> > 
> > 我将路径“/”改为“\”后没有语法错误了，不过还是有问题
> > ![image](https://user-images.githubusercontent.com/18391426/98886415-fe1b5880-24ce-11eb-8115-d81cf655c854.png)
> > ![image](https://user-images.githubusercontent.com/18391426/98886427-06739380-24cf-11eb-8399-950863fff88b.png)
> > ![image](https://user-images.githubusercontent.com/18391426/98886470-1db28100-24cf-11eb-9061-4166e399d744.png)
> 
> 你需要提前安装imagemagick，参考这里https://imagemagick.org/script/download.php

之前就有安装了
![image](https://user-images.githubusercontent.com/18391426/98891692-ab936980-24d9-11eb-8709-bc00db190697.png)

**Comment by gnmmdk** [comment]
> > > @gnmmdk 抱歉，这个是路径分隔符的问题，脚本里的是mac系统下的路径分隔符"/"，如果你是windows系统的话需要把里面的路径“/”全转换为“\”（这个后续会优化尽量避免这个问题）。另外你的输入路径不需要加引号，直接用--dir PNG_Sequence
> > 
> > 
> > 我将路径“/”改为“\”后没有语法错误了，不过还是有问题
> > ![image](https://user-images.githubusercontent.com/18391426/98886415-fe1b5880-24ce-11eb-8115-d81cf655c854.png)
> > ![image](https://user-images.githubusercontent.com/18391426/98886427-06739380-24cf-11eb-8399-950863fff88b.png)
> > ![image](https://user-images.githubusercontent.com/18391426/98886470-1db28100-24cf-11eb-9061-4166e399d744.png)
> 
> 你需要提前安装imagemagick，参考这里https://imagemagick.org/script/download.php

之前就有安装了

E:\AS_Workspace\XMVVWORK>magick -version
Version: ImageMagick 7.0.10-37 Q16 x64 2020-11-07 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2018 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Visual C++: 192729112
Features: Cipher DPC HDRI Modules OpenCL OpenMP(2.0)
Delegates (built-in): bzlib cairo flif freetype gslib heic jng jp2 jpeg lcms lqr lzma openexr pangocairo png ps raw rsvg tiff webp xml zlib

**Comment by gnmmdk** [comment]
![image](https://user-images.githubusercontent.com/18391426/98893665-e4cdd880-24dd-11eb-88a7-84f336ca3700.png)

**Comment by aceprcet** [comment]
@gnmmdk windows版本的imagemagick把convert命令改成了magick，因此需要把脚本里的convert指令都改成magick

**Comment by gnmmdk** [comment]
> magick

改完后有些其他的错误
![image](https://user-images.githubusercontent.com/18391426/98900992-e4d5d480-24ed-11eb-9707-aaf3d8bc34b2.png)
![image](https://user-images.githubusercontent.com/18391426/98901006-ef906980-24ed-11eb-8d18-5b4311abeedf.png)

**Comment by DymanZy** [comment]
转换脚本在windows环境还没验证过，后期我们在再支持一个windows版本的， @gnmmdk 如果你已经解决这个问题了，也欢迎跟我们分享~
