### ISSUE TITLE
这样的方案，礼物动效只能盖在所有View的最上层吧

### ISSUE THREAD

**Issue by gongshoudao** [bytedance/AlphaPlayer#2]
GLSurfaceview透明必须ZOrderOnTop，不知用TextureView能否解决这个问题

**Comment by DymanZy** [comment]
可以用GLTextureView解决，实际上我们最初的版本也是基于GLTextureView实现的

**Comment by gongshoudao** [comment]
> 可以用GLTextureView解决，实际上我们最初的版本也是基于GLTextureView实现的

最终没用GLTextureView，是处于性能考虑吗，或者是有其它的坑？

**Comment by DymanZy** [comment]
嗯嗯，有部分是出于性能和包大小的考虑，切到GLSurfaceView cpu可以下降5%，aar大小可以减少30KB；不过使用GLTextureView在以前的经验中也没有太大的兼容性问题；我们后续会支持上GLTextureView的实现

**Comment by crazy1235** [comment]
用GLTextureView 的话有什么包大小的考虑呢？

**Comment by DymanZy** [comment]
Android只是支持了TextureView，要使用GLTextureView需要额外引入，对库体积有影响，不过其实也可以忽略吧，在AlphaPlayer:1.0.2 版本中已经实现了对GLTextureView的支持，应该可以帮到你们~ @gongshoudao @crazy1235

**Comment by ruiAndroid** [comment]
AlphaVideoViewType 设置为GL_SURFACE_VIEW之后，视频没有在最上层播放，请问是为什么呢？

**Comment by DymanZy** [comment]
@ruiAndroid 可以检查一下你的设置呢，正常设置的话应该是播放在最上层的，看你的描述感觉像是使用了GL_TEXTURE_VIEW。

**Comment by ruiAndroid** [comment]
您好，感谢你们的回复，该问题已经解决，是视频本身的原因，使用你们的convertAlphaVideo脚本生成的视频就没有问题了，我们的应用是基于TV的，目前还发现了使用GL_TEXTURE_VIEW背景是黑色，GL_SURFACE_VIEW正常，我们的播放器是基于IJK封装的，目前在电视平台上硬解不通过，你们提供的ExoPlayer也是一样的情况，软解的话内存和cpu资源占用又很严重

**Comment by ruiAndroid** [comment]
您好，请问能否提供下你们原始视频的源文件呢，也就是右边的彩色视频部分，感谢

**Comment by DymanZy** [comment]
@ruiAndroid 使用GL_TEXTURE_VIEW背景是黑色的设备机型可以提供一下？

**Comment by DymanZy** [comment]
@ruiAndroid GLTextureView黑屏问题转到这个issue跟进吧 -> https://github.com/bytedance/AlphaPlayer/issues/9
