### ISSUE TITLE
动态addView显示不了，只有我一个人遇到吗？

### ISSUE THREAD

**Issue by hehanjie** [bytedance/AlphaPlayer#20]

**Comment by DymanZy** [comment]
可以提供更多的信息？

**Comment by chinkeikin** [comment]
我曾经遇到过初始化后立马调用播放会出现不显示的情况，后来我在PlayerController#handleMessage的SURFACE最后添加了一个mPlayerAction?.onPlayerReady()回调，并在接收到这个回调时播放视频解决这个问题

**Comment by DymanZy** [comment]
@hehanjie 验证了一下 @sinkkin 提及的场景确实可以复现，我们会在近期修复这个问题

**Comment by DymanZy** [comment]
@hehanjie @sinkkin 1.0.6版本上修复了这个问题了，感谢反馈~ [撒花]
