### ISSUE TITLE
关于视频转换中alpha通道的问题

### ISSUE THREAD

**Issue by gb18030** [bytedance/AlphaPlayer#22]
我看了下视频转换的处理脚本，有一点不明白：
separateAlphaChannel函数中将png的alpha通道保存到jpg中 
jpg是没有alpha通道的 后来又将像素中的R与原视频进行混合,为什么是R呢,而且项目中片段着色器中取的是G通道
if (vTextureCoord.x >= 0.5) {
        color2Map = texture2D(sTexture, vec2(vTextureCoord.x - 0.5, vTextureCoord.y));
        gl_FragColor = vec4(color.r, color.g, color.b, color2Map.g);
}
麻烦作者有时间的话解答一下 谢谢

**Comment by DymanZy** [comment]
@gb18030 可以分四步理解：
step 1: xxx01.png的像素点(r1, g1, b1, a1)通过removeAlpha函数得到xxx01_src.jpg像素点(r1, g1, b1)
step 2: xxx01.png的像素点(r1, g1, b1, a1)通过separateAlphaChannel函数得到xxx01_alpha.jpg像素点(a1, a1, a1)
step 3: 通过appendImageLand将xxx01_alpha.jpg和xxx01_src.jpg拼接到一块，再将序列帧重新导成视频
step 4: 在端上通过片段着色器重新混合，color对应的是xxx01_src.jpg的像素点(r1, g1, b1)，color2Map对应的是xxx01_alpha.jpg的像素点(a1, a1, a1)，所以不管取color2Map.r还是color2Map.g，结果都是一样会得到(r1, g1, b1, a1)
