### ISSUE TITLE
部分动画黑影明显

### ISSUE THREAD

**Issue by PengZeHai** [bytedance/AlphaPlayer#23]
[test.zip](https://github.com/bytedance/AlphaPlayer/files/5544483/test.zip)

你好。我这边用了你们的透明动画框架https://github.com/bytedance/AlphaPlayer，发现个问题，部分动画黑影明显。
我觉得是视频解码因为16位对齐，导致像素采样有误差，这边想请教下有没有什么好办法处理。

有问题的视频在附件，因为视频是从右边采样透明通道的，我这边改了下纹理采样点位置

//修改后的片段着色器
#extension GL_OES_EGL_image_external : require
precision mediump float;
varying vec2 vTextureCoord;
uniform samplerExternalOES sTexture;

void main() {
    vec4 color = texture2D(sTexture, vTextureCoord);
    vec4 color2Map = vec4(1.0, 1.0, 1.0, 1.0);
    if (vTextureCoord.x <= 0.5) {
        color2Map = texture2D(sTexture, vec2(vTextureCoord.x + 0.5, vTextureCoord.y));
        gl_FragColor = vec4(color.r, color.g, color.b, color2Map.g);
    } else {
        gl_FragColor = vec4(color.r, color.g, color.b, color.a);
    }
}

//修改后的getZoomData
private static float[] getZoomData(float leftZoomRatio, float topZoomRatio, float rightZoomRatio, float bottomZoomRatio) {
    return new float[] {
            // X, Y, Z, U, V
            -1.0f + leftZoomRatio * 2, -1.0f + bottomZoomRatio * 2, 0, 0.0f, 0.0f,
            1.0f - rightZoomRatio * 2, -1.0f + bottomZoomRatio * 2, 0, 0.5f, 0.f,
            -1.0f + leftZoomRatio * 2, 1.0f - topZoomRatio * 2, 0, 0.0f, 1.f,
            1.0f - rightZoomRatio * 2, 1.0f - topZoomRatio * 2, 0, 0.5f, 1.f,
    };
}

**Comment by DymanZy** [comment]
@PengZeHai 嗯嗯，大概率就是播放器解码位数对齐的问题，可以将视频宽度设置为16的倍数来规避

**Comment by PengZeHai** [comment]
只能设计那边做保证吗？能否我们程序这边做兼容，不然提供给别人用，都得让他们设计做保证。模拟器解码没有16位对齐，就没问题，真机就有这个问题

**Comment by DymanZy** [comment]
@PengZeHai 另一个方案就是由播放器去兼容了，这样的话就需要提供一个支持8位乃至16位解码自适应的播放器给他们接入

**Comment by PengZeHai** [comment]
https://vites.app/article/dev/763e0905.html
这边看到有位大佬，是通过计算出对齐后纹理的真实位置，获取正确的像素点
但我这边试了下，发现还是有问题

**Comment by gb18030** [comment]
可以考虑如下解决办法：
通过ffmpeg:
 ./ffprobe -print_format json -show_streams .\test.mp4

获取关键输出信息：
            "width": 600,
            "height": 950,
            "coded_width": 608,
            "coded_height": 960,
可以将实际的解码缓冲区配置到config.json中 然后做根据差值在片段着色器中做读取偏移处理
亦或是如果项目中已经带了ffmpeg的so 也可以直接获取然后再进行上述处理

**Comment by PengZeHai** [comment]
> 可以考虑如下解决办法：
> 通过ffmpeg:
> ./ffprobe -print_format json -show_streams .\test.mp4
> 
> 获取关键输出信息：
> "width": 600,
> "height": 950,
> "coded_width": 608,
> "coded_height": 960,
> 可以将实际的解码缓冲区配置到config.json中 然后做根据差值在片段着色器中做读取偏移处理

**Comment by PengZeHai** [comment]
@gb18030 这个集成门槛就有点高了

**Comment by ViTess** [comment]
@PengZeHai 

> https://vites.app/article/dev/763e0905.html
> 这边看到有位大佬，是通过计算出对齐后纹理的真实位置，获取正确的像素点
> 但我这边试了下，发现还是有问题

这个是我写的，你的视频我用自己的代码跑没有问题

[SVID_20201116_161825_1.zip](https://github.com/bytedance/AlphaPlayer/files/5544978/SVID_20201116_161825_1.zip)

你修改后的shader是怎样的？我估计还是写的有问题

**Comment by PengZeHai** [comment]
@ViTess 大佬好

attribute vec4 vPosition;
attribute vec4 vTexCoordinate;
uniform mat4 textureTransform;
varying vec2 l_TexCoordinate;
varying vec2 r_TexCoordinate;

void main () {
     l_TexCoordinate = (textureTransform * vTexCoordinate).xy;
     float midX =  (textureTransform * vec4(0.5, 0.0, 0.0, 0.0)).x;
     r_TexCoordinate = vec2(l_TexCoordinate.x + midX, l_TexCoordinate.y);
     gl_Position = vPosition;
}

#extension GL_OES_EGL_image_external : require
precision mediump float;
uniform samplerExternalOES texture;
varying vec2 l_TexCoordinate;
varying vec2 r_TexCoordinate;

void main () {
    vec4 color = texture2D(texture, l_TexCoordinate);
    vec4 alpha = texture2D(texture, vec2(r_TexCoordinate.x, r_TexCoordinate.y));
    gl_FragColor = vec4(color.rgb, alpha.r);
}

我是这样写的，能不能看看您的demo代码

**Comment by ViTess** [comment]
你的机器时什么？
textureTransform这个变换矩阵的值打印看下？
另外vec2可以加上highp，有些机型计算精度不够

我的代码公司业务在用，不能po

**Comment by PengZeHai** [comment]
@ViTess 红米k20 pro、小米6都有这问题
这是变换矩阵的值
[0.98355263,0.0,0.0,0.0,
0.0,-0.9875,0.0,0.0,
0.0,0.0,1.0,0.0,
0.0016447369,0.98854166,0.0,1.0]

**Comment by ViTess** [comment]
> @ViTess 大佬好
> 
> attribute vec4 vPosition;
> attribute vec4 vTexCoordinate;
> uniform mat4 textureTransform;
> varying vec2 l_TexCoordinate;
> varying vec2 r_TexCoordinate;
> 
> void main () {
> l_TexCoordinate = (textureTransform * vTexCoordinate).xy;
> float midX = (textureTransform * vec4(0.5, 0.0, 0.0, 0.0)).x;
> r_TexCoordinate = vec2(l_TexCoordinate.x + midX, l_TexCoordinate.y);
> gl_Position = vPosition;
> }
> 
> #extension GL_OES_EGL_image_external : require
> precision mediump float;
> uniform samplerExternalOES texture;
> varying vec2 l_TexCoordinate;
> varying vec2 r_TexCoordinate;
> 
> void main () {
> vec4 color = texture2D(texture, l_TexCoordinate);
> vec4 alpha = texture2D(texture, vec2(r_TexCoordinate.x, r_TexCoordinate.y));
> gl_FragColor = vec4(color.rgb, alpha.r);
> }
> 
> 我是这样写的，能不能看看您的demo代码

中点的值计算时w要设为1，即(0.5 ,0.0 , 0.0 , 1.0)
理论上矩阵计算时xy的值应该不受w影响，但是opengl官方推荐默认w默认为1，应该是w的值影响到gpu计算精度了。

**Comment by PengZeHai** [comment]
@ViTess 可以了！！！果然是这个问题，把w设为1就可以了，非常感谢大佬。
@gb18030 @DymanZy 按 @ViTess 大佬的做法https://vites.app/article/dev/763e0905.html，可以不用在播放器解码那里处理！！

**Comment by DymanZy** [comment]
可以的，我也验证一下，没问题的话同步到release版本上，感谢两位~ @PengZeHai @ViTess
