### ISSUE TITLE
片段着色器是否代码冗余？

### ISSUE THREAD

**Issue by gb18030** [bytedance/AlphaPlayer#24]
在TextureCropUtil中有如下代码或类似代码:
return new float[] {
                // X, Y, Z, U, V
                -1.0f + leftZoomRatio * 2, -1.0f + bottomZoomRatio * 2, 0, 0.5f, 0.f,
                1.0f - rightZoomRatio * 2, -1.0f + bottomZoomRatio * 2, 0, 1.f, 0.f,
                -1.0f + leftZoomRatio * 2, 1.0f - topZoomRatio * 2, 0, 0.5f, 1.f,
                1.0f - rightZoomRatio * 2, 1.0f - topZoomRatio * 2, 0, 1.f, 1.f,
        };
也就是说片段着色器的vTextureCoord中x坐标的取值是[0.5-1]
那么这个if判断是否是多余的?
if (vTextureCoord.x >= 0.5) {
        color2Map = texture2D(sTexture, vec2(vTextureCoord.x - 0.5, vTextureCoord.y));
        gl_FragColor = vec4(color.r, color.g, color.b, color2Map.g);
    } else {
        gl_FragColor = vec4(color.r, color.g, color.b, color.a);
    }

**Comment by PengZeHai** [comment]
我也觉得是只需要这部分就行
color2Map = texture2D(sTexture, vec2(vTextureCoord.x - 0.5, vTextureCoord.y));
gl_FragColor = vec4(color.r, color.g, color.b, color2Map.g);

**Comment by DymanZy** [comment]
实际上确实不会走到另一个条件分支，但是考虑到片段着色器和跟坐标映射的代码不在同一块，避免不必要的困惑就保留了if判断了
