### ISSUE TITLE
如果能像SVGA一样，直接加载Url播放就完美了

### ISSUE THREAD

**Issue by hehanjie** [bytedance/AlphaPlayer#25]

**Comment by sangxb** [comment]
大佬有自己Fork一份代码，支持网络URL么？

**Comment by hehanjie** [comment]
我们只是自己做了下载，再播放




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bytedance/AlphaPlayer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月24日(星期四) 晚上6:25
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [bytedance/AlphaPlayer] 如果能像SVGA一样，直接加载Url播放就完美了 (#25)





 
大佬有自己Fork一份代码，支持网络URL么？

**Comment by dxmwl** [comment]
> 我们只是自己做了下载，再播放
> […](#)

可以参考一下你们下载的这一部分吗？
