### ISSUE TITLE
iOS：在动画结束以前调用stop，会出现内存泄露的问题。

### ISSUE THREAD

**Issue by iStarEternal** [bytedance/AlphaPlayer#52]
查找后是多线程加锁引起的。
```
BDAlphaPlayerAssetReaderOutput.mm
- (void)drainSampleBufferQueue {}
- (void)fillBufferQueueIfNeed {}
```
在调用drain方法之后，fill内部仍然会执行，nextSampleBuffer没能释放。

**Comment by iStarEternal** [comment]
已提PR
未合并之前遇到问题的小伙伴请参考：
https://github.com/iStarEternal/AlphaPlayer/tree/fix/stackoverflow

**Comment by iStarEternal** [comment]
这项目是不是没人维护了？

**Comment by Fwahan** [comment]
亲，可以使用tag: 1.2.2 ，已解决内存泄漏问题

**Comment by iStarEternal** [comment]
> 亲，可以使用tag: 1.2.2 ，已解决内存泄漏问题

OK
