### ISSUE TITLE
全面屏下的残留帧问题

### ISSUE THREAD

**Issue by chengzijian** [bytedance/AlphaPlayer#6]
小米K20，设置全面屏，在使用GL_SURFACE_VIEW模式播放视频的时候，上滑屏幕进入手机桌面，在切回应用。会有帧残留
![QQ截图20200907171911](https://user-images.githubusercontent.com/6936576/92371619-672ccb80-f12e-11ea-9f29-254ab7a8b455.png)

**Comment by DymanZy** [comment]
@chengzijian 这个问题我们在小米10开启系统手势之后也遇到过，联系厂商了解到是系统实现的原因，在MIUI12之后这块改为原生方案了，应该就修复了这个问题，但是我们还没有测试过，你可以升级小米系统试试

**Comment by chengzijian** [comment]
升级MIUI12之后问题解决； 
另外发现在华为P30 EMUI10.1.0上也会偶现此问题，不必现
