### ISSUE TITLE
不斷地 allocate memory 造成 crash

### ISSUE THREAD

**Issue by dolphinsue319** [bytedance/AlphaPlayer#63]
iOS, 1.2.0 版
問題發生在 -[BDAlphaPlayerAssetReaderOutput fillBufferQueueIfNeed] 上，在這裡會一直不斷地 allocate memory, 所以影片播個一陣子，手機因為記憶體不夠用就 crash 了。

讓一段影片不斷地重覆播放再用 Instruments 裡的 Allocations 可以看出來。

**Comment by iStarEternal** [comment]
可參考解決方案：#52

**Comment by Fwahan** [comment]
可以使用tag: 1.2.2 ，已解决内存泄漏问题
