### ISSUE TITLE
为啥没有iOS版？

### ISSUE THREAD

**Issue by ywx372421496** [bytedance/AlphaPlayer#7]
想比对下大牛们是怎么写的，不管是swift还是OC

**Comment by DymanZy** [comment]
@ywx372421496 iOS的同学已经在准备开源工作，相信10月份就推出来~

**Comment by ywx372421496** [comment]
> @ywx372421496 iOS的同学已经在准备开源工作，相信10月份就推出来~

666

**Comment by qq326646683** [comment]
期待期待

**Comment by pashanhenlei** [comment]
> @ywx372421496 iOS的同学已经在准备开源工作，相信10月份就推出来~

跳票了？
