### ISSUE TITLE
为什么不直接用webm格式呢？

### ISSUE THREAD

**Issue by tbruceyu** [bytedance/AlphaPlayer#8]
webm格式天生支持yuva420P，每一帧直接就能播放透明的视频，而且AE可以直接导出。感觉这个实现不怎么好。而且抖音肯定不可能是用的MediaPlayer播放的，因为这个有兼容性问题和一些崩溃无法修复，项目里应该还有一部分播放器的没有开源出来吧。

**Comment by DymanZy** [comment]
@tbruceyu 目前mp4格式基本是兼容性最好的格式之一了，在Android/iOS和web端都有很好的支持，在我们看来兼容稳定性和表现能力mp4都要好一些；另外再我们项目中确实是使用自研的点播播放器的，MediaPlayer在国内一些厂商的手机上确实有部分兼容性问题，所以我们在开源的Demo中引入了ExoPlayer的支持，可以解决绝大部分的问题，当然如果你们也有自研播放器的话自然也是建议你们基于自研播放器实现AbsPlayer呢

**Comment by tbruceyu** [comment]
那在Web端的这种礼物动效怎么展示呢？

**Comment by DymanZy** [comment]
其实在我们业务场景中没有web端的case，后续开源的会包括iOS端和视频制作工具（熟悉AE的话其实不需要这套工具）。短时间内应该还不会考虑支持web端，但是核心思路是相通的，如果你需要的话，可以了解一下VideoRender.kt、frag.sh及vertex.sh这几个文件的逻辑，然后使用WebGL重新实现即可。

**Comment by peerless2012** [comment]
最近也碰到这个需求，根据我的调研，webm本身Android可以硬解，但是不支持透明度，iOS好像不支持硬解webm，所以跨平台有问题。

当然，Chrome等浏览器好像内置了webm的解码器，大多数浏览器都支持带透明度的webm了。

**Comment by tbruceyu** [comment]
> 

可以用软解来实现吧。

**Comment by peerless2012** [comment]
> > 
> 
> 可以用软解来实现吧。

软解缺少一个可用的解码库，现在软解的代码是在chrome里面的，需要拆出来。

其实我觉得关键的一个问题是，即使你把软解弄出来了，用软解来播放1080甚至更高分辨率的视频，软解压力会非常大。所以用此仓库的方法，能用到硬解，cpu压力会小很多。

**Comment by tbruceyu** [comment]
> 

嗯，就看具体的应用场景了。礼物场景一般720P的就完全够用了。

**Comment by tbruceyu** [comment]
> > > 
> > 
> > 
> > 可以用软解来实现吧。
> 
> 软解缺少一个可用的解码库，现在软解的代码是在chrome里面的，需要拆出来。
> 
> 其实我觉得关键的一个问题是，即使你把软解弄出来了，用软解来播放1080甚至更高分辨率的视频，软解压力会非常大。所以用此仓库的方法，能用到硬解，cpu压力会小很多。

https://chromium.googlesource.com/webm/libvpx/ 
我记得这个是可以直接编到ffmpeg里面去使用的吧

**Comment by shaobin0604** [comment]
> > > > 
> > > 
> > > 
> > > 可以用软解来实现吧。
> > 
> > 
> > 软解缺少一个可用的解码库，现在软解的代码是在chrome里面的，需要拆出来。
> > 其实我觉得关键的一个问题是，即使你把软解弄出来了，用软解来播放1080甚至更高分辨率的视频，软解压力会非常大。所以用此仓库的方法，能用到硬解，cpu压力会小很多。
> 
> https://chromium.googlesource.com/webm/libvpx/ 我记得这个是可以直接编到ffmpeg里面去使用的吧

@tbruceyu 参考这个 https://github.com/zxzx74147/ExoPlayer

**ExoPlayer transparency support with vp9!**

- The branch is: https://github.com/zxzx74147/ExoPlayer/tree/dev-v2-r2.11.8-transparency
- How to use: https://github.com/zxzx74147/ExoPlayer/blob/dev-v2-r2.11.8-transparency/USING.md
- Demo apk: https://github.com/zxzx74147/ExoPlayer/releases/download/r2.11.8_transparency/demo-withExtensions-release.apk

**Comment by peerless2012** [comment]
看起来还是把vpx的解码器编译到exoplayer的扩展中，看了下代码应该是软解，实际测了下，真的是软解，高分辨率直接卡的要死，所以这个方案还是不太行。
