### ISSUE TITLE
使用GLTextureView在部分机型上有黑屏问题

### ISSUE THREAD

**Issue by DymanZy** [bytedance/AlphaPlayer#9]
复现设备：小米10

**Comment by DymanZy** [comment]
AlphaPlayer:1.0.3  版本已修复GLTextureView的黑屏问题🎉🎉🎉~

**Comment by whytry-GAR** [comment]
大佬。这边在1.0.6版本有遇到类似的问题，部分机型（可以用mumu模拟器复现）播放前，attach那下会闪下黑屏。然后才正常播放，请问有什么方式可以处理吗
